// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: sportevent/sportevent.proto

package sportevent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventVisibleStatus int32

const (
	EventVisibleStatus_EVENT_VISIBLE_STATUS_UNSPECIFIED EventVisibleStatus = 0
	EventVisibleStatus_EVENT_VISIBLE_STATUS_ALL         EventVisibleStatus = 1
	EventVisibleStatus_EVENT_VISIBLE_STATUS_VISIBLE     EventVisibleStatus = 2
	EventVisibleStatus_EVENT_VISIBLE_STATUS_INVISIBLE   EventVisibleStatus = 3
)

// Enum value maps for EventVisibleStatus.
var (
	EventVisibleStatus_name = map[int32]string{
		0: "EVENT_VISIBLE_STATUS_UNSPECIFIED",
		1: "EVENT_VISIBLE_STATUS_ALL",
		2: "EVENT_VISIBLE_STATUS_VISIBLE",
		3: "EVENT_VISIBLE_STATUS_INVISIBLE",
	}
	EventVisibleStatus_value = map[string]int32{
		"EVENT_VISIBLE_STATUS_UNSPECIFIED": 0,
		"EVENT_VISIBLE_STATUS_ALL":         1,
		"EVENT_VISIBLE_STATUS_VISIBLE":     2,
		"EVENT_VISIBLE_STATUS_INVISIBLE":   3,
	}
)

func (x EventVisibleStatus) Enum() *EventVisibleStatus {
	p := new(EventVisibleStatus)
	*p = x
	return p
}

func (x EventVisibleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventVisibleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sportevent_sportevent_proto_enumTypes[0].Descriptor()
}

func (EventVisibleStatus) Type() protoreflect.EnumType {
	return &file_sportevent_sportevent_proto_enumTypes[0]
}

func (x EventVisibleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventVisibleStatus.Descriptor instead.
func (EventVisibleStatus) EnumDescriptor() ([]byte, []int) {
	return file_sportevent_sportevent_proto_rawDescGZIP(), []int{0}
}

type EventSortByField int32

const (
	EventSortByField_EVENT_SORT_BY_FIELD_UNSPECIFIED EventSortByField = 0
	EventSortByField_EVENT_SORT_BY_FIELD_ID          EventSortByField = 1
	EventSortByField_EVENT_SORT_BY_FIELD_NAME        EventSortByField = 2
	EventSortByField_EVENT_SORT_BY_FIELD_VISIBLE     EventSortByField = 3
	EventSortByField_EVENT_SORT_BY_FIELD_TIME        EventSortByField = 4
)

// Enum value maps for EventSortByField.
var (
	EventSortByField_name = map[int32]string{
		0: "EVENT_SORT_BY_FIELD_UNSPECIFIED",
		1: "EVENT_SORT_BY_FIELD_ID",
		2: "EVENT_SORT_BY_FIELD_NAME",
		3: "EVENT_SORT_BY_FIELD_VISIBLE",
		4: "EVENT_SORT_BY_FIELD_TIME",
	}
	EventSortByField_value = map[string]int32{
		"EVENT_SORT_BY_FIELD_UNSPECIFIED": 0,
		"EVENT_SORT_BY_FIELD_ID":          1,
		"EVENT_SORT_BY_FIELD_NAME":        2,
		"EVENT_SORT_BY_FIELD_VISIBLE":     3,
		"EVENT_SORT_BY_FIELD_TIME":        4,
	}
)

func (x EventSortByField) Enum() *EventSortByField {
	p := new(EventSortByField)
	*p = x
	return p
}

func (x EventSortByField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSortByField) Descriptor() protoreflect.EnumDescriptor {
	return file_sportevent_sportevent_proto_enumTypes[1].Descriptor()
}

func (EventSortByField) Type() protoreflect.EnumType {
	return &file_sportevent_sportevent_proto_enumTypes[1]
}

func (x EventSortByField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventSortByField.Descriptor instead.
func (EventSortByField) EnumDescriptor() ([]byte, []int) {
	return file_sportevent_sportevent_proto_rawDescGZIP(), []int{1}
}

// Request for ListEvents call.
type ListEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *ListEventsRequestFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sportevent_sportevent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sportevent_sportevent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_sportevent_sportevent_proto_rawDescGZIP(), []int{0}
}

func (x *ListEventsRequest) GetFilter() *ListEventsRequestFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response to ListEvents call.
type ListEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*SportEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sportevent_sportevent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sportevent_sportevent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_sportevent_sportevent_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsResponse) GetEvents() []*SportEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Filter for listing events.
type ListEventsRequestFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventIds      []int64            `protobuf:"varint,1,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	VisibleStatus EventVisibleStatus `protobuf:"varint,2,opt,name=visible_status,json=visibleStatus,proto3,enum=sportevent.EventVisibleStatus" json:"visible_status,omitempty"`
	SortBy        EventSortByField   `protobuf:"varint,3,opt,name=sort_by,json=sortBy,proto3,enum=sportevent.EventSortByField" json:"sort_by,omitempty"`
}

func (x *ListEventsRequestFilter) Reset() {
	*x = ListEventsRequestFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sportevent_sportevent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEventsRequestFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequestFilter) ProtoMessage() {}

func (x *ListEventsRequestFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sportevent_sportevent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequestFilter.ProtoReflect.Descriptor instead.
func (*ListEventsRequestFilter) Descriptor() ([]byte, []int) {
	return file_sportevent_sportevent_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsRequestFilter) GetEventIds() []int64 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *ListEventsRequestFilter) GetVisibleStatus() EventVisibleStatus {
	if x != nil {
		return x.VisibleStatus
	}
	return EventVisibleStatus_EVENT_VISIBLE_STATUS_UNSPECIFIED
}

func (x *ListEventsRequestFilter) GetSortBy() EventSortByField {
	if x != nil {
		return x.SortBy
	}
	return EventSortByField_EVENT_SORT_BY_FIELD_UNSPECIFIED
}

// A sport event.
type SportEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID represents a unique identifier for the event.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name is the official name given to the event.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Visible represents whether or not the event is visible.
	Visible bool `protobuf:"varint,3,opt,name=visible,proto3" json:"visible,omitempty"`
	// AdvertisedStartTime is the time the event is advertised to run.
	AdvertisedStartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=advertised_start_time,json=advertisedStartTime,proto3" json:"advertised_start_time,omitempty"`
}

func (x *SportEvent) Reset() {
	*x = SportEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sportevent_sportevent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportEvent) ProtoMessage() {}

func (x *SportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sportevent_sportevent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SportEvent.ProtoReflect.Descriptor instead.
func (*SportEvent) Descriptor() ([]byte, []int) {
	return file_sportevent_sportevent_proto_rawDescGZIP(), []int{3}
}

func (x *SportEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SportEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SportEvent) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *SportEvent) GetAdvertisedStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AdvertisedStartTime
	}
	return nil
}

var File_sportevent_sportevent_proto protoreflect.FileDescriptor

var file_sportevent_sportevent_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x11, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3b, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x12,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x53, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0xb4, 0x01, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x12, 0x45, 0x0a, 0x0e, 0x76,
	0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x0d, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x22, 0x9a, 0x01, 0x0a, 0x0a, 0x53, 0x70,
	0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x76,
	0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x4e, 0x0a, 0x15, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x13, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x64, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x9e, 0x01, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a,
	0x20, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x56, 0x49, 0x53, 0x49, 0x42, 0x4c, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x56, 0x49, 0x53,
	0x49, 0x42, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x10,
	0x01, 0x12, 0x20, 0x0a, 0x1c, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x56, 0x49, 0x53, 0x49, 0x42,
	0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x56, 0x49, 0x53, 0x49, 0x42, 0x4c,
	0x45, 0x10, 0x02, 0x12, 0x22, 0x0a, 0x1e, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x56, 0x49, 0x53,
	0x49, 0x42, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x49,
	0x53, 0x49, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x2a, 0xb0, 0x01, 0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x23, 0x0a, 0x1f,
	0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59, 0x5f, 0x46, 0x49,
	0x45, 0x4c, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x5f,
	0x42, 0x59, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x1c, 0x0a,
	0x18, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59, 0x5f, 0x46,
	0x49, 0x45, 0x4c, 0x44, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x02, 0x12, 0x1f, 0x0a, 0x1b, 0x45,
	0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59, 0x5f, 0x46, 0x49, 0x45,
	0x4c, 0x44, 0x5f, 0x56, 0x49, 0x53, 0x49, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x1c, 0x0a, 0x18,
	0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59, 0x5f, 0x46, 0x49,
	0x45, 0x4c, 0x44, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x04, 0x32, 0x56, 0x0a, 0x05, 0x53, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x4d, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x1d, 0x2e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sportevent_sportevent_proto_rawDescOnce sync.Once
	file_sportevent_sportevent_proto_rawDescData = file_sportevent_sportevent_proto_rawDesc
)

func file_sportevent_sportevent_proto_rawDescGZIP() []byte {
	file_sportevent_sportevent_proto_rawDescOnce.Do(func() {
		file_sportevent_sportevent_proto_rawDescData = protoimpl.X.CompressGZIP(file_sportevent_sportevent_proto_rawDescData)
	})
	return file_sportevent_sportevent_proto_rawDescData
}

var file_sportevent_sportevent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sportevent_sportevent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sportevent_sportevent_proto_goTypes = []interface{}{
	(EventVisibleStatus)(0),         // 0: sportevent.EventVisibleStatus
	(EventSortByField)(0),           // 1: sportevent.EventSortByField
	(*ListEventsRequest)(nil),       // 2: sportevent.ListEventsRequest
	(*ListEventsResponse)(nil),      // 3: sportevent.ListEventsResponse
	(*ListEventsRequestFilter)(nil), // 4: sportevent.ListEventsRequestFilter
	(*SportEvent)(nil),              // 5: sportevent.SportEvent
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_sportevent_sportevent_proto_depIdxs = []int32{
	4, // 0: sportevent.ListEventsRequest.filter:type_name -> sportevent.ListEventsRequestFilter
	5, // 1: sportevent.ListEventsResponse.events:type_name -> sportevent.SportEvent
	0, // 2: sportevent.ListEventsRequestFilter.visible_status:type_name -> sportevent.EventVisibleStatus
	1, // 3: sportevent.ListEventsRequestFilter.sort_by:type_name -> sportevent.EventSortByField
	6, // 4: sportevent.SportEvent.advertised_start_time:type_name -> google.protobuf.Timestamp
	2, // 5: sportevent.Sport.ListEvents:input_type -> sportevent.ListEventsRequest
	3, // 6: sportevent.Sport.ListEvents:output_type -> sportevent.ListEventsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sportevent_sportevent_proto_init() }
func file_sportevent_sportevent_proto_init() {
	if File_sportevent_sportevent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sportevent_sportevent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sportevent_sportevent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sportevent_sportevent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEventsRequestFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sportevent_sportevent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SportEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sportevent_sportevent_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sportevent_sportevent_proto_goTypes,
		DependencyIndexes: file_sportevent_sportevent_proto_depIdxs,
		EnumInfos:         file_sportevent_sportevent_proto_enumTypes,
		MessageInfos:      file_sportevent_sportevent_proto_msgTypes,
	}.Build()
	File_sportevent_sportevent_proto = out.File
	file_sportevent_sportevent_proto_rawDesc = nil
	file_sportevent_sportevent_proto_goTypes = nil
	file_sportevent_sportevent_proto_depIdxs = nil
}
